# Codecov configuration for RAG File Processor
# Enforces 85% per-file coverage for trunk-based development

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  # Overall project coverage target
  range: "85..100"
  round: down
  precision: 2

  # Coverage status checks
  status:
    # Overall project coverage
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
        if_ci_failed: error
    
    # Changes/patch coverage
    patch:
      default:
        target: 85%
        threshold: 1%
        base: auto
        if_ci_failed: error

# PR comments configuration
comment:
  layout: "header, diff, files, tree"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  show_carryforward_flags: false

# Ignore files and directories
ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "**/conftest.py"
  - "setup.py"
  - "docker_deployment/**/*"
  - "*.md"
  - "*.txt"
  - "*.yml"
  - "*.yaml"

# Flag configuration for different test types
flags:
  unittests:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/
    carryforward: false

# GitHub integration
github_checks:
  annotations: true