# Development-specific overrides for docker-compose.yml
# This file is automatically loaded when running docker-compose in development

services:
  rag-file-processor:
    # Enable development features
    environment:
      # Development-specific environment variables
      - LOG_LEVEL=DEBUG
      - ENABLE_DOCUMENT_PROCESSING=true
      - MODEL_VENDOR=google  # Default to Google for development
      
    # Development volume mounts for hot reloading (if needed)
    volumes:
      # Override: Add source code mounting for development (uncomment if needed)
      # - ./src:/app/src:ro
      # - ./main.py:/app/main.py:ro
      # - ./CLAUDE.md:/app/CLAUDE.md:ro
      
      # Development-specific data persistence
      - ./data/chroma_db_dev:/app/data/chroma_db
      
    # Development resource limits (more permissive)
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
          
    # Development health check (more frequent)
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Development services (uncomment as needed)
  
  # Optional: ChromaDB standalone server for development
  # chroma-server:
  #   image: chromadb/chroma:latest
  #   container_name: kiro-chroma-dev
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./data/chroma_server:/chroma/chroma
  #   environment:
  #     - CHROMA_SERVER_HOST=0.0.0.0
  #     - CHROMA_SERVER_HTTP_PORT=8000
  #   networks:
  #     - kiro-network

# Development-specific network configuration
networks:
  mcp-network:
    external: true