name: mcp-network

services:
  rag-file-processor:
    image: ghcr.io/ronsonw/kiro_project:latest
    container_name: rag-file-processor
    restart: unless-stopped
    
    environment:
      # Application settings - container paths (mapped from host)
      - SOURCE_FOLDER=/app/data/source
      - SAVED_FOLDER=/app/data/saved
      - ERROR_FOLDER=/app/data/error
      - LOG_LEVEL=INFO
      
      # Temporary directory settings for document processing
      - TMPDIR=/tmp/unstructured
      - TEMP=/tmp/unstructured
      - TMP=/tmp/unstructured
      - HOME=/home/appuser
      
      # API Keys (injected by deployment scripts)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # ChromaDB Configuration
      - CHROMA_CLIENT_MODE=${CHROMA_CLIENT_MODE:-embedded}
      - CHROMA_DB_PATH=${CHROMA_DB_PATH:-./data/chroma_db}
      - CHROMA_SERVER_HOST=${CHROMA_SERVER_HOST}
      - CHROMA_SERVER_PORT=${CHROMA_SERVER_PORT}
      - CHROMA_COLLECTION_NAME=${CHROMA_COLLECTION_NAME:-rag-kb}
      
    volumes:
      # Map local folders to container data directories (set by deployment scripts)
      - ${SOURCE_FOLDER}:/app/data/source
      - ${SAVED_FOLDER}:/app/data/saved 
      - ${ERROR_FOLDER}:/app/data/error
      # Persist ChromaDB data and logs locally
      - ../data/chroma_db:/app/data/chroma_db
      - ../logs:/app/logs
      - ../config:/app/config:ro
      # Temporary directory for document processing
      - /tmp/file-processor-unstructured:/tmp/unstructured  # Unix/Mac
      # For Windows, use: C:\temp\file-processor-unstructured:/tmp/unstructured
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - mcp-network

networks:
  mcp-network:
    external: true

volumes:
  kiro_data:
    driver: local