# CI Deployment docker-compose configuration
# Uses pre-built images from GitHub Container Registry
# Based on shared configuration but customized for CI deployment

services:
  rag-file-processor:
    # Use pre-built image from GHCR instead of building locally
    image: ${DOCKER_IMAGE:-ghcr.io/ronsonw/kiro_project:latest}
    container_name: rag-file-processor-ci
    restart: unless-stopped
    
    environment:
      # Application settings - container paths (mapped from host)
      - SOURCE_FOLDER=/app/data/source
      - SAVED_FOLDER=/app/data/saved
      - ERROR_FOLDER=/app/data/error
      - LOG_LEVEL=INFO
      
      # Temporary directory settings for document processing
      - TMPDIR=/tmp/unstructured
      - TEMP=/tmp/unstructured
      - TMP=/tmp/unstructured
      - HOME=/home/appuser
      
      # Document processing settings (injected by deployment scripts)
      - ENABLE_DOCUMENT_PROCESSING=${ENABLE_DOCUMENT_PROCESSING:-true}
      - DOCUMENT_PROCESSOR_TYPE=${DOCUMENT_PROCESSOR_TYPE:-rag_store}
      - MODEL_VENDOR=${MODEL_VENDOR:-google}
      
      # File monitoring configuration (Docker-optimized)
      - FILE_MONITORING_MODE=${FILE_MONITORING_MODE:-auto}
      - POLLING_INTERVAL=${POLLING_INTERVAL:-2.0}
      - DOCKER_VOLUME_MODE=${DOCKER_VOLUME_MODE:-true}
      
      # API Keys (injected by deployment scripts)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # ChromaDB Configuration
      - CHROMA_CLIENT_MODE=${CHROMA_CLIENT_MODE:-embedded}
      - CHROMA_DB_PATH=${CHROMA_DB_PATH:-./data/chroma_db}
      - CHROMA_SERVER_HOST=${CHROMA_SERVER_HOST}
      - CHROMA_SERVER_PORT=${CHROMA_SERVER_PORT}
      - CHROMA_COLLECTION_NAME=${CHROMA_COLLECTION_NAME:-rag-kb}
      
    volumes:
      # Map local folders to container data directories (set by deployment scripts)
      - ${SOURCE_FOLDER}:/app/data/source
      - ${SAVED_FOLDER}:/app/data/saved 
      - ${ERROR_FOLDER}:/app/data/error
      # Persist ChromaDB data and logs locally (relative to ci/ directory)
      - ../data/chroma_db:/app/data/chroma_db
      - ../logs:/app/logs
      - ../shared/config:/app/config:ro
      # Temporary directory for document processing
      - /tmp/file-processor-unstructured:/tmp/unstructured  # Unix/Mac
      # For Windows, use: C:\temp\file-processor-unstructured:/tmp/unstructured
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  kiro_data_ci:
    driver: local